# pip install numpy

In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
np.array([1, 2, 3, 4, 32.321])

array([ 1.   ,  2.   ,  3.   ,  4.   , 32.321])

In [5]:
arr = np.array([1, 2, 3, 4, 32.321])
arr, arr.dtype

(array([ 1.   ,  2.   ,  3.   ,  4.   , 32.321]), dtype('float64'))

In [6]:
arr = np.array([1, 2, 3, 4, 32.321], dtype=np.int8)
arr, arr.dtype

(array([ 1,  2,  3,  4, 32], dtype=int8), dtype('int8'))

In [ ]:
arr = np.array([1, 2, 3, 4, 32.321], dtype=np.int8)
arr, arr.dtype

In [19]:
arr = np.array([1, 2, 3, 4, 32.321, "hello"])
arr, arr.dtype

(array(['1', '2', '3', '4', '32.321', 'hello'], dtype='<U32'), dtype('<U32'))

In [7]:
bin(1)

'0b1'

In [9]:
for i in range(17):
    print(i, " in binar: ", bin(i)[2:])

0  in binar:  0
1  in binar:  1
2  in binar:  10
3  in binar:  11
4  in binar:  100
5  in binar:  101
6  in binar:  110
7  in binar:  111
8  in binar:  1000
9  in binar:  1001
10  in binar:  1010
11  in binar:  1011
12  in binar:  1100
13  in binar:  1101
14  in binar:  1110
15  in binar:  1111
16  in binar:  10000


In [10]:
2 ** 8

256

# 0..255 (pozitive)

In [13]:
arr = np.array([1, 2, 3, 4, 255], dtype=np.uint8)

In [14]:
arr = np.array([1, 2, 3, 4, 256], dtype=np.uint8)

OverflowError: Python integer 256 out of bounds for uint8

# -128..127 (il contine si pe 0)

In [15]:
arr = np.array([1, 2, 3, 4, 127, -128], dtype=np.int8)

In [16]:
arr = np.array([1, 2, 3, 4, 128, -128], dtype=np.int8)

OverflowError: Python integer 128 out of bounds for int8

In [17]:
arr = np.array([1, 2, 3, 4, 124, -129], dtype=np.int8)

OverflowError: Python integer -129 out of bounds for int8

# Operatii cu numpy

In [21]:
arr = np.array([20, 30, 40, 50, 60])
arr

array([20, 30, 40, 50, 60])

In [22]:
arr + 3

array([23, 33, 43, 53, 63])

In [23]:
arr * 2

array([ 40,  60,  80, 100, 120])

In [24]:
arr  > 30

array([False, False,  True,  True,  True])

In [25]:
arr [ arr  > 30 ]

array([40, 50, 60])

In [26]:
arr [ arr % 10 ]

array([20, 20, 20, 20, 20])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(100, 200)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [30]:
np.arange(10, 20, 5)

array([10, 15])